apiVersion: v1
kind: Service
metadata:
  name: {{ include "pp-chart.fullname" . -}}{{- .Values.backend.nameTag }}
  namespace: default
  labels:
    {{- include "pp-chart.labels" . | nindent 4 }}
    app: pp
    tier: backend
spec:
  ports:
    - protocol: TCP
      # The port this service will be available on.
      # Must match frontend nginx conf file setting.
      port:  {{ .Values.backend.service.port }}
      # The container port the service will forward to.
      # Named in pod spec in deployment yaml.
      targetPort: {{ .Values.backend.deployment.portName }}
  selector:
    {{- include "pp-chart.selectorLabels" . | nindent 4 }}
    app: pp
    tier: backend
  type: {{ .Values.backend.service.type }}
  sessionAffinity: None
