apiVersion: v1
kind: Service
metadata:
  name: {{ include "pp-chart.fullname" . -}}{{- .Values.frontend.nameTag }}
  namespace: default
  labels:
    {{- include "pp-chart.labels" . | nindent 4 }}
    app: pp
    tier: frontend
  {{- with .Values.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - protocol: TCP
      # The port this service will be available is on.
      # External url comes in on this port.
      port:  {{ .Values.frontend.service.port }}
      # The container port the service will forward to.
      # Named in pod spec in deployment yaml.
      targetPort: {{ .Values.frontend.deployment.portName }}
  selector:
    {{- include "pp-chart.selectorLabels" . | nindent 4 }}
    app: pp
    tier: frontend
  type: {{ .Values.frontend.service.type }}
  sessionAffinity: None
