kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "pp-chart.fullname" . }}-frontend-deployment
  namespace: default
  labels:
    {{- include "pp-chart.labels" . | nindent 4 }}
    app: pp
    tier: frontend
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "pp-chart.selectorLabels" . | nindent 6 }}
      app: pp
      tier: frontend
  # Describes the pods that will be created.
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "pp-chart.selectorLabels" . | nindent 8 }}
        app: pp
        tier: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pp-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # For skaffold to work, this must be a .Values reference - this is replaced by the same reference in artifactOverrides in skaffold.yaml. 
          image:  {{ .Values.frontend.image }} 
          # Note: If set to 'Always' will fail on Minikube
          # 'Always' may avoid caching issues when making changes?
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.frontend.deployment.portName }}
              # Frontend server must be open on this port
              containerPort: {{ .Values.frontend.deployment.portValue }}
              protocol: TCP
          env:
            # Used when running envSubst on the nginx configuration
            - name: service
              value: {{ include "pp-chart.fullname" . }}-backend-service
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
